### ISSUE TITLE
Images look really low quality

### ISSUE THREAD

**Issue by yavko** [JakeStanger/ironbar#96] opened 2023-04-03 00:12 UTC
**Describe the bug**

icons and cover art look blurry, hidpi issue perhaps?

**Expected behavior**

images are displayed at the right resolution

**System information:**
 - Distro: NixOS 23.05
- Compositor: Hyprland
 - Ironbar version: master at `0.11`

**Additional context**

probably hidpi

**Screenshots**

icon ![image](https://user-images.githubusercontent.com/15178513/229386557-eda707db-e0de-40ec-a47a-82694f788667.png)
another icon (only play is icon) 
![image](https://user-images.githubusercontent.com/15178513/229386596-60b1bef1-3cac-42ef-949a-4c1e16eecedf.png)

**Comment by JakeStanger** [comment] 2023-04-03 21:26
What's your config for the images / how are you loading them / what resolution are they? 

Images are loaded at a hard-coded width/height at the moment, so will be resized automatically to that size. That could cause issues.

**Comment by yavko** [comment] 2023-04-04 01:41
> What's your config for the images / how are you loading them / what resolution are they?
> 
> Images are loaded at a hard-coded width/height at the moment, so will be resized automatically to that size. That could cause issues.

Well, these are icons from an icon theme, and come from papirus, which is 100% vector.

**Comment by JakeStanger** [comment] 2023-04-04 22:07
Ah, so are they all stored as SVGs?

**Comment by yavko** [comment] 2023-04-04 22:30
Yeah

**Comment by JakeStanger** [comment] 2023-04-07 11:33
Cool, I suspect there's something weird going on with that then, perhaps related to hidpi as you suggest. Are you able to try bitmap images (literally any appropriately sized image will do just to test) and see if you still get the same problem?

**Comment by JakeStanger** [comment] 2023-04-22 21:36
I've just merged #120 which means you can now set `icon_size` on modules, and it will render images at that size. When you get a chance, can you try the latest master and see if setting a size larger than the default (24 for `music`) helps at all?

**Comment by yavko** [comment] 2023-04-22 21:39
> I've just merged #120 which means you can now set `icon_size` on modules, and it will render images at that size. When you get a chance, can you try the latest master and see if setting a size larger than the default (24 for `music`) helps at all?
> 
> I also tested with Papirus myself and had no issues before/after, which does point to hidpi.

On it! Just need to compile :/

**Comment by yavko** [comment] 2023-04-22 22:03
Doesn't work, just renders it giantly, same with cover art
![image](https://user-images.githubusercontent.com/15178513/233808327-101e110a-6d3c-4ffd-aef4-19200c283a16.png)

**Comment by JakeStanger** [comment] 2023-04-22 22:06
Yeah, images are all loaded with pixbufs. I don't think I'm setting the display scale anywhere, so that may well be it.

**Comment by yavko** [comment] 2023-04-22 22:10
> Yeah, images are all loaded with pixbufs. I don't think I'm setting the display scale anywhere, so that may well be it.

This is how i did it in gtk4, though `os_icon` is a `GtkPicture` not `GtkImage`
![image](https://user-images.githubusercontent.com/15178513/233808568-66562143-5a8b-4d1e-aeda-ba21c12ebff7.png)

**Comment by yavko** [comment] 2023-04-22 22:14
> > Yeah, images are all loaded with pixbufs. I don't think I'm setting the display scale anywhere, so that may well be it.
> 
> This is how i did it in gtk4, though `os_icon` is a `GtkPicture` not `GtkImage` ![image](https://user-images.githubusercontent.com/15178513/233808568-66562143-5a8b-4d1e-aeda-ba21c12ebff7.png)

I just remembered why I did it like this, I did it like this, because I was rendering a tiny icon as a giant image

**Comment by JakeStanger** [comment] 2023-04-22 22:23
Looks like there's a separate method in GTK3 that they must have renamed to be default in GTK4. Hopefully it's as easy as that and the linked PR sorts it.

**Comment by yavko** [comment] 2023-04-22 22:25
> Looks like there's a separate method in GTK3 that they must have renamed to be default in GTK4. Hopefully it's as easy as that and the linked PR sorts it.

Me too 😬, compile time :3

**Comment by JakeStanger** [comment] 2023-04-22 22:29
> compile time :3

If you haven't set up [sccache](https://github.com/mozilla/sccache) I'd recommend it - it can help a lot with frequent compiles

**Comment by yavko** [comment] 2023-04-22 22:31
> > compile time :3
> 
> If you haven't set up [sccache](https://github.com/mozilla/sccache) I'd recommend it - it can help a lot with frequent compiles

I used to have it setup, but idk how to use it with the nix build system, i'll try to do some research on it now lol

**Comment by JakeStanger** [comment] 2023-04-22 22:33
Ah of course, that could be an interesting one with nix. I guess an ad-hoc repo clone with a shell env could probably speed it up too?

**Comment by yavko** [comment] 2023-04-22 22:40
Okay this is superrr weird, still blurry (also i removed the icon size stuff should i re-add it?)
![image](https://user-images.githubusercontent.com/15178513/233810596-48e1dda1-6b38-470f-96d8-1e0b6587c702.png)
![image](https://user-images.githubusercontent.com/15178513/233810594-9eacf66f-738f-4eae-b275-2c6c88682552.png)

**Comment by JakeStanger** [comment] 2023-04-22 22:44
Argh. If you try a different theme, does it still occur?

> also i removed the icon size stuff should i re-add it?

Yeah worth a shot I guess.

> Also it can't be a gtk thing, because this doesn't happen in eww, maybe we can look at its source?

Yeah good idea, seems as good a place to poke around

---

I do have a laptop that's got a 4K screen, but it's on Gnome on X11 at the moment. I think I'll need to set that up when I get time (probs tomorrow) and see if I can replicate/fix it on there.

**Comment by yavko** [comment] 2023-04-22 22:58
No difference, breeze doesn't change, icon size doesnt as well, also i just noticed this error which has been happening for a while, (checked back at logs)
![image](https://user-images.githubusercontent.com/15178513/233811028-ba383e65-acc0-463d-81cd-cdc568ff7732.png)

**Comment by JakeStanger** [comment] 2023-04-22 23:03
Aha, that looks might suspicious. Have a look at sections 17.12.1.3 and 17.12.1.4 [here](https://nixos.org/manual/nixpkgs/stable/#sec-language-gnome). A quick google pointed me to those, which sounds relevant?

**Comment by yavko** [comment] 2023-04-22 23:06
> Aha, that looks might suspicious. Have a look at sections 17.12.1.3 and 17.12.1.4 [here](https://nixos.org/manual/nixpkgs/stable/#sec-language-gnome). A quick google pointed me to those, which sounds relevant?

Omg, is this why? I'll add it as dep to flake and test 
![image](https://user-images.githubusercontent.com/15178513/233811260-6bd85e11-83bb-4315-b8ba-bb5d936b13ae.png)

**Comment by yavko** [comment] 2023-04-22 23:11
> > Aha, that looks might suspicious. Have a look at sections 17.12.1.3 and 17.12.1.4 [here](https://nixos.org/manual/nixpkgs/stable/#sec-language-gnome). A quick google pointed me to those, which sounds relevant?
> 
> Omg, is this why? I'll add it as dep to flake and test ![image](https://user-images.githubusercontent.com/15178513/233811260-6bd85e11-83bb-4315-b8ba-bb5d936b13ae.png)

Turns out its already there, i actually need to add a preFixup

**Comment by yavko** [comment] 2023-04-23 02:53
My pr mostly fixes the issue, I think I know why eww doesn't have this same issue even tho it doesn't include the `preFixUp` stuff. I think its because it doesn't use pixbufs for images, in fact it doesn't handle images at all afaik, you give it properties and widget and it will handle those properties directly in gtk, so no taking image or icon and then feeding it into a pixbuf like its done here

**Comment by JakeStanger** [comment] 2023-04-23 10:00
Oh interesting okay, that sounds definitely worth looking into. I'll merge both our PRs because they're steps in the right direction, and I'll leave this issue open to see if I can do what eww's doing and fully resolve it.

**Comment by JakeStanger** [comment] 2023-04-23 10:21
> I think its because it doesn't use pixbufs for images, in fact it doesn't handle images at all afaik

Looks like this isn't the case unfortunately :(

https://github.com/elkowar/eww/blob/e76206817de1cb86ec431dcff7d4b04c8b7d36fc/crates/eww/src/widgets/widget_definitions.rs#L517-L518

**Comment by yavko** [comment] 2023-04-23 20:54
> > I think its because it doesn't use pixbufs for images, in fact it doesn't handle images at all afaik
> 
> Looks like this isn't the case unfortunately :(
> 
> [elkowar/eww@`e762068`/crates/eww/src/widgets/widget_definitions.rs#L517-L518](https://github.com/elkowar/eww/blob/e76206817de1cb86ec431dcff7d4b04c8b7d36fc/crates/eww/src/widgets/widget_definitions.rs#L517-L518)

That's weird, then why didn't it have blurry images

**Comment by JakeStanger** [comment] 2023-04-24 21:39
I think I'm going to need to locally test this to get to the bottom of it. I've tried to set sway up on my laptop but Zorin still ships an ancient version that doesn't support the required wlr protocols :/

I suppose I could put Nix to good use here. Are you able to share your nix config (or at least just the relevant parts of it), and then I can just apply your config on my laptop and (in theory) get a replica environment to test.

**Comment by yavko** [comment] 2023-04-24 22:37
So I use 3200x1800, which is almost 4k. Also my NixOS dotfiles are public on GitHub, they haven't been updated in a while, so when I'll get home I'll push all my local changes.

**Comment by yavko** [comment] 2023-04-25 05:26
> So I use 3200x1800, which is almost 4k. Also my NixOS dotfiles are public on GitHub, they haven't been updated in a while, so when I'll get home I'll push all my local changes.

Okay so I added all my local changes earlier here is link just in case https://github.com/yavko/Dotfiles

**Comment by JakeStanger** [comment] 2023-04-30 17:30
I've managed to get NixOS with your dotfiles running on my laptop, and I can confirm the play icon looks blurry for me too, in both Hyprland and Sway.

My plan next is to have a play with the config/CSS and see if I can get anywhere that way. I'll also test on another distro when I have time to spend setting that up, and see if it occurs there (or if you have something set up where you can do that, that'd be very helpful).

---

As an aside, it is very awesome that after a few minor tweaks, I can have a near-exact replica of your full system up and running on my machine.

**Comment by yavko** [comment] 2023-04-30 21:14
> and I can confirm the play icon looks blurry for me too, in both Hyprland and Sway.

I'm glad it's not just my system

> As an aside, it is very awesome that after a few minor tweaks, I can have a near-exact replica of your full system up and running on my machine.

Nix is great, totally reproducible, that's why I use it!

**Comment by yavko** [comment] 2023-05-01 08:26
Btw, I added some new stuff to my config for hovering, also fixes uptime not working https://github.com/yavko/Dotfiles/commit/892525329bd229220ee88d4f4d76b0d1c0de797a#diff-c9239733f0cccdf366d64d7b5c2106980017e8b2c54eb42a305cc85bee53e970

**Comment by JakeStanger** [comment] 2023-05-07 13:47
Ok! One painful install of Arch Linux later, I can confirm it's happening on there as well. I do at least now have a testing ground, so hopefully I can finally get to the bottom of this soon.

**Comment by JakeStanger** [comment] 2023-05-08 15:10
I think! ***Think!*** I've got it

**Comment by yavko** [comment] 2023-05-08 15:15
> I think! ***Think!*** I've got it. Weirdly no safe Rust API for it, so took a bit of digging.

Can't wait to test it once I get home!

**Comment by yavko** [comment] 2023-05-09 09:07
It works!!!!

**Closed** 2023-05-09 11:01 UTC
Labels: bug
