### ISSUE TITLE
[Sys Info] Add used memory to be shown in MiB

### ISSUE THREAD

**Issue by Schweber** [JakeStanger/ironbar#319] opened 2023-09-28 13:02 UTC
**Is your feature request related to a problem? Please describe.**
According to the [documentation](https://github.com/JakeStanger/ironbar/wiki/sys-info), the used memory can only be shown in GiB. I would like to be able to see it in MiB, because GiB is too coarse for me.

**Comment by JakeStanger** [comment] 2023-09-28 21:38
Hey, yeah I do plan to add that when I look at the other sys info issues. Because it's similar enough to #149 I'll close this as duplicate and update that to reflect units in general.

**Comment by JakeStanger** [comment] 2023-09-28 21:39
Duplicate of #149

**Closed** 2023-09-28 21:39 UTC
Labels: enhancement

**Comment by Schweber** [comment] 2023-10-11 12:58
Ok thank you! If someone wants this functionality in the meantime, i solved it like this:

```
type = "script"
cmd = "echo $(free -m | grep Mem | awk '{print $3}')M"    
mode = "poll"
interval = 2000
```
