### ISSUE TITLE
Sysinfo memory in megabytes

### ISSUE THREAD

**Issue by awalone995** [JakeStanger/ironbar#778] opened 2024-11-16 01:50 UTC
**Is your feature request related to a problem? Please describe.**

This isn't very useful
![image](https://github.com/user-attachments/assets/62d58e4a-84be-4b17-9b49-75d1756eb5fc)

**Describe the solution you'd like**
Display in finer units

**Comment by JakeStanger** [comment] 2024-11-16 10:20
Duplicate of #149

**Closed** 2024-11-16 10:20 UTC
Labels: duplicate, enhancement
