### ISSUE TITLE
[Tray] Submenus for tray icons don't open

### ISSUE THREAD

**Issue by chmanie** [JakeStanger/ironbar#455] opened 2024-02-14 23:53 UTC
**Describe the bug**
When using the NetworkManager `nm-applet` or the udiskie applet the submenus that are supposed to open when hovering over the main menu item do not open (or at least are not visible).

**To Reproduce**
1. Use the tray module
2. Have `nm-applet` or udiskie running
3. Click the NetworkManager applet and hover over "Available connections" or "VPN connections" or click the udiskie applet and hover over "Managed devices" 
4. The submenus are not opening

**Expected behavior**
> The submenus should open

**System information:**
 - Distro: NixOS 23.05 6.7.4-zen1
- Compositor: Sway 1.8.1
 - Ironbar version: 0.15.0-pre or 0.14.1

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```json
{
  "end": [
    {
      "type": "tray"
    }
  ]
}
```
</details>

<details><summary>Styles</summary>
No style sheet
</details>

**Screenshots**
![issue](https://github.com/JakeStanger/ironbar/assets/2174084/2d62c770-dd69-4564-96ab-9cc620d6fe92)

**Comment by JakeStanger** [comment] 2024-02-25 17:59
Looks like this was a regression of the recent tray fixes, and should be resolved in #470

**Closed** 2024-03-17 14:12 UTC
Labels: bug
