### ISSUE TITLE
Add on_click_left and on_click_right to volume widget

### ISSUE THREAD

**Issue by henriqpsantos** [JakeStanger/ironbar#725] opened 2024-09-06 10:49 UTC
**Is your feature request related to a problem? Please describe.**
Currently the Volume widget only allows for the ironbar default popup to be displayed, and to use an alternative (such as a pavucontrol scratchpad) requires the reimplementation of the widget.

**Describe the solution you'd like**
I'd like the on_click_left and on_click_right to be added, such that the tooltip/widget that is displayed can be replaced with a gui option such as pavucontrol.

**Describe alternatives you've considered**
Creating the volume widget myself and configuring it from there. But this seems like overkill for what is essentially 2 additional options.

**Comment by JakeStanger** [comment] 2024-09-11 09:32
This will be implemented, but closing as this is a duplicate of #692.

**Closed by JakeStanger** 2024-09-11 09:32 UTC
Labels: enhancement
