### ISSUE TITLE
Failed to register: Timeout was reached

### ISSUE THREAD

**Issue by TheSunCat** [JakeStanger/ironbar#168] opened 2023-05-28 11:29 UTC
**Describe the bug**
Ironbar does not start

**To Reproduce**
1. Run ironbar
2. Observe it not starting

**Expected behavior**
ironbar starts

**System information:**
 - Distro: Arch Linux
- Compositor: Hyprland
 - Ironbar version: v0.12.0.r36.ge036ff0-1

**Configuration**
> Share your bar configuration and stylesheet as applicable:

<details><summary>Config</summary>

```
let {

}
in {

}
```
</details>

**Additional context**
This started happening today. Ironbar has not been updated since yesterday when it was running fine.

**Logs**
```ini
[apm@apg ~]$ ironbar                                                                                     
2023-05-28T11:27:14.209791Z  INFO ironbar: 49: Ironbar version 0.12.1
2023-05-28T11:27:14.209804Z  INFO ironbar: 50: Starting application
Failed to register: Timeout was reached
2023-05-28T11:27:39.233424Z  INFO ironbar: 120: Shutting down
```

**Comment by TheSunCat** [comment] 2023-05-28 11:39
aaaand it's gone after a reboot. Not closing this yet in case the issue returns.

**Comment by JakeStanger** [comment] 2023-05-28 13:45
From a google it looks like this might be a rare GTK thing caused by another running instance. Doing `pkill ironbar` before restarting it, or rebooting, should consistently fix this.

**Comment by JakeStanger** [comment] 2023-06-18 15:37
Going to close this assuming it hasn't happened since. If you run into it again, let me know and I'll re-open.

**Closed** 2023-06-18 15:37 UTC
Labels: bug

**Comment by yavko** [comment] 2023-06-18 19:01
I think I've had this before too, but it disappeared after a reboot

**Comment by JakeStanger** [comment] 2023-06-18 19:19
Interesting, good to know.

I'll keep this closed for now since it still seems to point more to a weird rare GTK/compositor issue than anything else and there's a known fix.
